untitled2/music/urls.py
from django.urls import path
from django.conf.urls import include, url
from . import views


urlpatterns = [
    path('', views.index, name='index'),

    #/music/


    path('<int:album_id>/', views.detail, name='detail'),


    #/album_id/ favorite

    path('<int:album_id>/favorite/',views.favorite ,name='favorite')
]

untitled2/untitled2/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf.urls import url

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('music.urls')),

]

untitled2/music/models.py
from django.db import models

# Create your models here.

class Album(models.Model):
    artist = models.CharField(max_length=250)
    album_title = models.CharField(max_length=500)
    genre = models.CharField(max_length=100)
    album_logo = models.CharField(max_length=1000)

    def __str__(self):
        return self.album_title + ' - ' + self.artist


class Song(models.Model):
    album = models.ForeignKey(Album, on_delete=models.CASCADE)
    file_type = models.CharField(max_length=10)
    song_title = models.CharField(max_length=250)
    is_favorite = models.BooleanField(default=False)
    def __str__(self):
        return self.song_title

untitled2/music/views.py
from django.http import HttpResponse
from django.http import Http404
from .models import Album
from django.shortcuts import render
from django.template import loader


def index(request):
    #Connect DB
    all_albums = Album.objects.all()
    return render(request,'music/index.html', {'all_albums' : all_albums})

def detail(request, album_id):

    try:
        album = Album.objects.get(pk=album_id)
    except Album.DoesNotExist:
        raise Http404("Album does not exist")

    return render(request, 'music/detail.html', {'album': album})

def favorite(request, album_id):
    return ""

untitled2/music/templates/music/detail.html
<img src={{ album.album_logo }}>

<h1>{{ album.album_title }}</h1>
<h3>{{ album.artist }}</h3>

<ul>
    {% for song in album.song_set.all %}
    <li>
        {{ song.song_title }} - {{ song.file_type }}
    </li>
    {% endfor %}
</ul>


{% if error_message %}
    <p><strong>{{ error_message }}</strong></p>
{% endif %}

<form action="{% url 'music:favorite' album.id %}" method="post">
    {% csrf_token %}
    {% for song in album.song_set.all %}
        <input type="radio" id="song{{ forloop.counter }}" name="song" value="{{ song.id }}">
        <label for="song{{ forloop.counter }}">
            {{ song.song_title}}
            {% if song.is_favorite %}
                <img src ="https://i.imgur.com/rhZm0JE.jpg" />
            {% endif %}
        </label><br>

    {% endfor %}
    <input type="submit" value="Favorite">
</form>

untitled2/music/templates/music/index.html
{% if all_albums  %}

    Heres my albums
    <ul>
        {% for album in all_albums %}
        <li>
            <a href ="{% url 'detail' album.id %}">{{ album.album_title }} </a>
        </li>
        {% endfor %}
    </ul>
{% else %}
    <h3> You don't have any albums</h3>
{% endif %}